### PR TITLE
Added a different style for cards #13

### PR DESCRIPTION
**Pull request by anubhav1206**
Added a different style for cards with a hover animation and seamless transitions.

### CODE REVIEW

**Comment by lmas3009** [comment]
You also need to add one card related to your design on the documentation page also.

Can you add more designs like this
image

**Comment by lmas3009** [comment]
in docs.html

**Comment by anubhav1206** [comment]
> You also need to add one card related to your design on the documentation page also.
> 
> Can you add more designs like this image

Sure I'll do that

**Comment by anubhav1206** [comment]
> You also need to add one card related to your design on the documentation page also.
> 
> Can you add more designs like this image

Added, please check.

**Comment by lmas3009** [comment]
perfect. Thanks for your contribution

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
