### PR TITLE
Made navbar sticky(fixed to top) on scroll and added redirect link in logo text

### PR DESCRIPTION
**Pull request by bprathamesh20**
#Pull Request Description

Changes Made

-Made the navigation header sticky at the top of the page.
-Added a clickable logo text that redirects to a specified URL.

### CODE REVIEW

**Comment by lmas3009** [comment]
when it is on dark mode. Unable to view the header
image

**Comment by bprathamesh20** [comment]
Fixed the Issue 
image

**Comment by lmas3009** [comment]
Perfect 👍

**Comment by lmas3009** [comment]
Thanks for contributing
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
