### PR TITLE
Some Mods Done for Make Site A Bit responsive as per screen

### PR DESCRIPTION
**Pull request by shriekdj**
Please Validate the PR Request

### CODE REVIEW

**Comment by lmas3009** [comment]
@shriekdj  i just added some comments

**Comment by shriekdj** [comment]
> @shriekdj i just added some comments
but where @lmas3009 ...?

**Comment by shriekdj** [comment]
closes https://github.com/lmas3009/cleandocs-template/issues/2#issue-1103959941

**Comment by shriekdj** [comment]
also closes https://github.com/lmas3009/cleandocs-template/issues/3

**Comment by lmas3009** [comment]
Make these changes in #3.
After we can merge this pr.

**Comment by lmas3009** [comment]
Small update i change my hosting to netlify it will auto deploy.

So now remove all the cleandocs-template in all href tags

**Comment by shriekdj** [comment]
ok changing href for netlify

**Comment by shriekdj** [comment]
both requests of the issues are done for netlify

**Comment by lmas3009** [comment]
Thanks, @shriekdj.
For your contribution ❤.

**Pull request merged**
