### PR TITLE
style landing home page, add laptop image

### PR DESCRIPTION
**Pull request by NereidaRondon**
#16  Styled the Home page a bit, based off the image that was provided as reference.

### CODE REVIEW

**Comment by lmas3009** [comment]
When we turn on dark mode i can't see the text 
image

**Comment by NereidaRondon** [comment]
@lmas3009 I rectified the dark mode issue. Thank you so much! 🤓✨

**Comment by lmas3009** [comment]
perfect Thanks for designing and writing the script. Now the home page looks good.

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
