### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shriekdj**
Adding Visual Representation In README.md With GitHub's New Mermaid Flowchart in Markdown Files.

Please Watch The Preview First of README.md file in File Changed

### CODE REVIEW

**Comment by shriekdj** [comment]
The Will Look Like Below

**Comment by shriekdj** [comment]
# cleandocs-template
A documentation template built using HTML, Tailwindcss and Javascript


**Clone the repository**
```bash
git clone https://github.com/lmas3009/cleandocs-template.git
```

# Contributing

All code contributions - if you want change the ui -  must go through a pull request and be approved by a core developer before being merged. This is to ensure a proper review of all the code.

After making changes add your information in contributors section in index.html

We truly ❤️ pull requests! If you wish to help.

✅  &nbsp; Add your information on website, please follow [Contribution Guide](https://github.com/lmas3009/cleandocs-template/blob/master/CONTRIBUTING.md)

# Visual Representation
```mermaid
flowchart TD
  A[lmas3009/cleandocs-template] --> B{Get This Repo};
  B -- By Fork --> C[yourusername/cleandocs-template];
  B -- By Clone --> D[Your Local Repo];
  C ----> E[Create New Branch];
  D ----> E[Create New Branch];
  E --> F[Made Some Changes];
  F --> G[Commit Changes];
  G -- On GitHub --> H[Create Pull Request];
  H -- If Rejected -- Made Changes Again --> F;
  H -- If Approved --> I[Changes Done]
```

# Copyright and license
The MIT License (MIT) http://www.opensource.org/licenses/mit-license.php

**Comment by lmas3009** [comment]
thanks for contribution
keep contributing and happy coding...

**Comment by lmas3009** [comment]
i will merge and close the pr

**Pull request merged**
